= 리뷰 API

=== 전체 목록 (/api/posts/*)

[cols=2*]
|===
| 기능 | API

| <<피드 생성>> | POST /api/posts
| <<피드 조회>> | GET /api/posts/{postId}
| <<인근 지역 피드 전체 조회>> | GET /api/posts?latitude={latitude}&longitude={longitude}&level={level}&page={page}
| <<피드 스크랩>> | POST /api/posts/scrap
| <<피드 삭제>> | DELETE /api/posts/{postId}
| <<피드 좋아요>> | PUT /api/posts/{postId}
| <<피드 좋아요 취소>> | PUT /api/posts/{postId}

|===

=== 피드 생성

API : `POST /api/posts`

피드를 생성합니다.
(단, 로그인 유저만 가능)

==== `200 OK`

===== Request

operation::create-post[snippets='http-request,request-fields']

===== `Response`

operation::create-post[snippets='http-response,response-fields']

=== 피드 조회

API : `GET /api/posts/{postId}`

피드를 조회합니다.
(익명사용자도 조회 가능)

==== `200 OK`

===== Request

operation::find-post[snippets='http-request,path-parameters']

===== `Response`

operation::find-post[snippets='http-response,response-fields']

=== 전체 피드 조회

API : `GET /api/posts?latitude=37.565494&longitude=126.992493&level=7&page=0`

인근 지역의 모든 피드를 조회합니다.
(익명사용자도 조회 가능)

==== `200 OK`

===== Request

operation::find-all-post[snippets='http-request,request-parameters']

===== `Response`

operation::find-all-post[snippets='http-response,response-fields']

=== 전체 스크랩

API : `POST /api/posts/scrap`

피드를 스크랩 합니다.
(단, 로그인 유저만 가능)

==== `200 OK`

===== Request

operation::scrap-post[snippets='http-request,request-fields']

===== `Response`

operation::scrap-post[snippets='http-response,response-fields']

=== 피드 삭제

API : `DELETE /api/posts/{postId}`

피드를 삭제합니다.
(단, 로그인 유저만 가능)

==== `200 OK`

===== Request

operation::delete-post[snippets='http-request,path-parameters']

===== `Response`

operation::delete-post[snippets='http-response,response-fields']
