== 전체 목록 (/api/posts/*)

[cols=2*]
|===
| 기능 | API

| <<리뷰 생성>> | POST /api/posts
| <<리뷰 조회>> | GET /api/posts/{postId}
| <<인근 지역 리뷰 전체 조회>> | GET /api/posts?latitude={latitude}&longitude={longitude}&level={level}&page={page}
| <<리뷰 스크랩>> | POST /api/posts/scrap

|===

=== 리뷰 생성

API : `POST /api/posts`

리뷰를 생성합니다.
(단, 로그인 유저만 가능)

==== `200 OK`

===== Request

operation::create-post[snippets='http-request,request-fields']

===== `Response`

operation::create-post[snippets='http-response,response-fields']

=== 리뷰 조회

API : `GET /api/posts/{postId}`

리뷰를 조회합니다.
(익명사용자도 조회 가능)

==== `200 OK`

===== Request

operation::find-post[snippets='http-request,path-parameters']

===== `Response`

operation::find-post[snippets='http-response,response-fields']

=== 전체 리뷰 조회

API : `GET /api/posts?latitude=37.565494&longitude=126.992493&level=7&page=0`

인근 지역의 모든 리뷰를 조회합니다.
(익명사용자도 조회 가능)

==== `200 OK`

===== Request

operation::find-all-post[snippets='http-request,request-parameters']

===== `Response`

operation::find-all-post[snippets='http-response,response-fields']

=== 전체 스크랩

API : `POST /api/posts/scrap`

피드를 스크랩 합니다.
(단, 로그인 유저만 가능)

==== `200 OK`

===== Request

operation::scrap-post[snippets='http-request,request-fields']

===== `Response`

operation::scrap-post[snippets='http-response,response-fields']
